universe = vanilla
log = logs/job.$(ClusterId).$(ProcId).log
error = logs/job.$(ClusterId).$(ProcId).stderr
output = logs/job.$(ClusterId).$(ProcId).stdout

executable = run_genRslt.sh
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R361.tar.gz, shared/Type/, shared/generateRslt.R
transfer_output_files = $(outfile)
transfer_output_remaps = "$(outfile)=../RESULT/$(outfile)"

request_cpus = 1
request_memory = 1GB
request_disk = 1GB

queue outfile from outname.txt
