universe = vanilla
log = logs/job.$(ClusterID).$(ProcID).log
error = logs/job.$(ClusterID).$(ProcID).stderr
output = logs/job.$(ClusterID).$(ProcID).stdout

executable = run_get4sim.sh
arguments = $(causalType) $(nsample) $(sim) $(A) $(B) 

max_idle = 1000
# requirements = !regexp(".*.(tropics|sips)",Machine) && IsUndefined(CONTAINER)
requirements = (OpSysMajorVer =?= 8)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/R413.tar.gz,http://proxy.chtc.wisc.edu/SQUID/SLIBS-el7.tar.gz, http://proxy.chtc.wisc.edu/SQUID/qhong8/packages_med.tar.gz, shared/

transfer_output_files = $(outfile)
transfer_output_remaps = "$(outfile)=../COMBSIM/shared/Type$(causalType)/$(outfile)"

periodic_hold = ((CurrentTime - EnteredCurrentStatus) > 1800) && (TransferringInput == True)
periodic_release = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 180) && (JobRunCount < 6) && ((HoldReasonCode == 13) || (HoldReasonCode == 3))

request_cpus = 1
request_memory = 1500MB
request_disk = 2GB

queue causalType,nsample,sim,A,B,outfile from input.txt
