universe = vanilla
log = logs/job.$(ClusterId).$(ProcId).log
error = logs/job.$(ClusterId).$(ProcId).stderr
output = logs/job.$(ClusterId).$(ProcId).stdout

executable = run_get4sim.sh
arguments = $(causalType) $(nsample) $(sim) $(A) $(B) 

max_idle = 2000
requirements = !regexp(".*.(tropics|sips)",Machine) && IsUndefined(CONTAINER)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R361.tar.gz, http://proxy.chtc.wisc.edu/SQUID/SLIBS.tar.gz, http://proxy.chtc.wisc.edu/SQUID/qhong8/packages.tar.gz, shared/
transfer_output_files = $(outfile)
transfer_output_remaps = "$(outfile)=../COMBSIM/shared/Type$(causalType)/$(outfile)"

periodic_hold = (((CurrentTime - EnteredCurrentStatus) > 900) && (TransferringInput == True)) || ((CurrentTime - EnteredCurrentStatus) > 3600*36)
periodic_release = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 180) && (JobRunCount < 6) && ((HoldReasonCode == 13) || (HoldReasonCode == 3))

request_cpus = 1
request_memory = 1500MB
request_disk = 2GB

queue causalType,nsample,sim,A,B,outfile from input.txt
